[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
