[build]
  command = "npm install --no-optional && npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD ./src"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true
