[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "true"
  VITE_SUPABASE_URL = "https://jrxxemchkytvqqsvloso.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyeHhlbWNoa3l0dnFxc3Zsb3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwOTMyNjMsImV4cCI6MjA0ODY2OTI2M30.rQegO5QBiNn-NztTcvFynHZ5yxvtdIcTVDXohaRQxbg"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
