[build]
  command = "npm install && npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD ./src"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true
